-- AlterTable
ALTER TABLE "User" ADD COLUMN     "pictureUrl" TEXT,
ADD COLUMN     "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
ALTER COLUMN "company" DROP NOT NULL,
ALTER COLUMN "country" DROP NOT NULL;
